stages:
  eda:
    cmd: python src/eda.py
    deps:
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Sample Solution.csv
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Train.csv
    outs:
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_count.png
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_frequency.png
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_count.png
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_frequency.png

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\src\eda.py
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Sample Solution.csv
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Train.csv
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Test.csv
    outs:
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\X_test.pickle
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\y_test.pickle
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\X_train.pickle
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\y_train.pickle
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\tfidf.pickle
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\test_true.csv
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\train.csv