stages:
  eda:
    cmd: python src/eda.py
    deps:
    - data_raw\BBC News Sample Solution.csv
    - data_raw\BBC News Train.csv
    outs:
    - plots\eda_plot_with_count.png
    - plots\eda_plot_with_frequency.png
    - plots\testdata_eda_plot_with_count.png
    - plots\testdata_eda_plot_with_frequency.png

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
    - src\eda.py
    - data_raw\BBC News Train.csv
   
    outs:
    - data\processed\X_test.pickle
    - data\processed\y_test.pickle
    - data\processed\X_train.pickle
    - data\processed\y_train.pickle
    - data\processed\tfidf.pickle
    - data\train.csv

  model_creating:
    cmd: python src/model_creating.py
    deps:
    - data\processed\X_test.pickle
    - data\processed\y_test.pickle
    - data\processed\X_train.pickle
    - data\processed\y_train.pickle
    - src\eda.py
  
    params:
    - logistic_regression.params.C
    - logistic_regression.params.class_weight
    - logistic_regression.params.multi_class
    - logistic_regression.params.penalty
    - logistic_regression.params.solver
    
    metrics:
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\reports\parameters.json:
        cache: false
    - E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\reports\scores.json:
        cache: false
    outs:
    - models\logistic_regression_model.pickle

  model_testing:
    cmd: python src/model_testing.py
    deps:
    - src\eda.py
    - data\processed\tfidf.pickle
    - models\logistic_regression_model.pickle 
    
    outs:
    - reports\test_report.json
