base:
  project_name: News Article Sorting
  target: Category
  random_state: 42

plot:
  eda_count_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_count.png
  eda_freq_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\eda_plot_with_frequency.png
  testdata_eda_count_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_count.png
  testdata_eda_freq_plot: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\plots\testdata_eda_plot_with_frequency.png

data_source:
  sample_submission: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Sample solution.csv
  train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Train.csv
  test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data_raw\BBC News Test.csv

load_data:
  X_train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\X_train.pickle
  X_test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\X_test.pickle
  y_train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\y_train.pickle
  y_test: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\y_test.pickle
  tfidf: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\processed\tfidf.pickle
  train: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\train.csv
  test_true: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\data\test_true.csv 


train_category:
  sport: 3
  tech: 1
  business: 0
  entertainment: 4
  politics: 2

tfidf:
  ngram_range: (1, 2)
  max_df: 1.0
  min_df: 10
  max_features: 300
  lowercase: False

logistic_regression:
  params:
    C: 0.9
    class_weight: balanced
    multi_class: multinomial
    penalty: l2
    solver: newton-cg
  save_model: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\models\logistic_regression_model.pickle

reports:
  parameters: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\reports\parameters.json
  scores: E:\DataScience_internship_with_ineuron\newsarticalesorting\newsarticlesorting\reports\scores.json